name: ci

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  pull_request:
    branches:
      - stable

jobs:
  linter:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"
      - name: Check zig is canonical
        shell: 'bash'
        run: zig fmt --check .

  maintainance:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"

      - name: Test updating
        shell: 'bash'
        run: zig build -Dupdate -Dverbose -freference-trace --verbose

  build:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
        os:
          - ubuntu-24.04
          - windows-2025
          - macos-15
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"

      - name: Test updating
        shell: 'bash'
        run: zig build -Dverbose -freference-trace --verbose

  user:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
        os:
          - ubuntu-24.04
          - windows-2025
          - macos-15
        repo:
          - cimgui
        exclude:
          # TODO: remove this exclude after Zig 0.17.0
          - zig-version: latest
            repo: cimgui
          # TODO: fail unexpectedly with an "Out of memory" error
          - os: windows-2025
            repo: cimgui
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"
          ref: "${{ github.event.pull_request.base.ref }}"

      - id: lastcommit
        shell: 'bash'
        run: |
          set -x
          printf 'sha=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}_${{ steps.lastcommit.outputs.sha }}"

      - name: Prepare ${{ matrix.repo }}.zig/build.zig.zon
        env:
          URL: "git+${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name }}#${{ github.event.pull_request.head.sha }}"
        shell: 'bash'
        run: zig fetch --save "${URL}"

      - name: Test building ${{ matrix.repo }}.zig
        env:
          REPO: "${{ matrix.repo }}"
        shell: 'bash'
        run: |
          set -x
          case "${REPO}" in
          ( 'cimgui' )
            renderers="$(zig build -Dlist-renderers -Dseparator=, -freference-trace --verbose)"
            renderers="${renderers:+"-Drenderers={${renderers}}"}"
            eval "zig build -Dverbose -Dplatforms=GLFW ${renderers} -freference-trace --verbose" ;;
          ( * ) zig build -Dverbose -freference-trace --verbose ;;
          esac

      - name: Test ${{ matrix.repo }}.zig examples
        env:
          REPO: "${{ matrix.repo }}"
        shell: 'bash'
        run: |
          set -x
          case "${REPO}" in
          ( 'cimgui' ) env -C ./examples zig build -freference-trace --verbose ;;
          ( * ) ;;
          esac
